package de.baumann.browser.vot;

/**
 * Phase 2: JS polyfill for GM_* APIs.
 * Covers full list from phase0-notes.md (1.11.8):
 * GM_xmlhttpRequest, GM.xmlHttpRequest, GM_getValue, GM_setValue, GM_deleteValue, GM_listValues,
 * GM.getValue, GM.getValues, GM.setValue, GM.deleteValue, GM.listValues,
 * GM_addValueChangeListener, GM_removeValueChangeListener, GM_addStyle, GM_notification, GM_info, window.focus
 * No unsafeWindow, no GM_registerMenuCommand.
 */
public class GmShim {
    public static String getShimJs() {
        return ""
                // GM_info polyfill (must be before vot.js)
                + "if (typeof GM_info === 'undefined') {"
                + "  window.GM_info = {"
                + "    downloadMode: 'native', isIncognito: false, sandboxMode: 'raw',"
                + "    script: {version: '1.11.8', name: 'VOT', namespace: 'vot'},"
                + "    scriptHandler: 'VOTBrowser', version: '1.11.8', scriptMetaStr: '', scriptWillUpdate: false, scriptUpdateURL: null"
                + "  };"
                + "  try { window.GM_info = window.GM_info; } catch(e){}"
                + "}"
                + "if (typeof globalThis.GM_info === 'undefined') { try { globalThis.GM_info = window.GM_info; } catch(e){} }"
                // GM_addStyle polyfill
                + "if (typeof GM_addStyle === 'undefined') {"
                + "  window.GM_addStyle = function(css){"
                + "    try { var s=document.createElement('style'); s.type='text/css'; s.textContent=css; (document.head||document.documentElement).appendChild(s); return s; } catch(e){ return null; }"
                + "  };"
                + "  try { globalThis.GM_addStyle = window.GM_addStyle; } catch(e){}"
                + "}"
                // GM_notification stub
                + "if (typeof GM_notification === 'undefined') { window.GM_notification = function(d){ try{ console.log('[GM_notification]', d); }catch(e){} }; }"
                + "if (typeof GM !== 'undefined' && typeof GM.notification === 'undefined') { GM.notification = window.GM_notification; }"
                // window.focus no-op
                + "try { window.focus = window.focus || function(){}; } catch(e){}"
                // core registry for GM_xhr
                + "window.__votGm = window.__votGm || { pending: {}, nextId: 1 };"
                + "window.__votGm.deliver = function(id, resp, kind){"
                + "  var opts = window.__votGm.pending[id];"
                + "  if (!opts) return;"
                + "  delete window.__votGm.pending[id];"
                + "  try {"
                + "    if (kind === 'load') {"
                + "      var r = resp;"
                + "      // Tampermonkey expects responseText, status, responseHeaders, finalUrl, readyState\n"
                + "      // Handle binary protobuf via base64 -> Blob (vot-worker returns arrayBuffer)\n"
                + "      if (r.responseBase64) {"
                + "        try {"
                + "          var binStr = atob(r.responseBase64);"
                + "          var len = binStr.length;"
                + "          var bytes = new Uint8Array(len);"
                + "          for (var i=0; i<len; i++) bytes[i] = binStr.charCodeAt(i);"
                + "          r.response = new Blob([bytes]);"
                + "          if (r.responseText === undefined || r.responseText === null || r.responseText.length === 0) r.responseText = binStr;"
                + "        } catch(e){ console.warn('GM deliver base64 decode failed', e); }"
                + "      }"
                + "      if (r.responseText === undefined && r.response !== undefined) r.responseText = r.response;"
                + "      if (r.readyState === undefined) r.readyState = 4;"
                + "      if (opts.onload) opts.onload(r);"
                + "      if (opts.onLoad) opts.onLoad(r);"
                + "    } else if (kind === 'error') {"
                + "      if (opts.onerror) opts.onerror(resp);"
                + "      if (opts.onError) opts.onError(resp);"
                + "    } else if (kind === 'timeout') {"
                + "      if (opts.ontimeout) opts.ontimeout(resp);"
                + "      if (opts.onTimeout) opts.onTimeout(resp);"
                + "    }"
                + "  } catch(e){ console.warn('GM deliver error', e); }"
                + "};"
                // GM_xmlhttpRequest callback style
                + "window.GM_xmlhttpRequest = window.GM_xmlhttpRequest || function(opts){"
                + "  try {"
                + "    if (!opts || !opts.url) { if (opts && opts.onerror) opts.onerror({error:'no url'}); return; }"
                + "    var id = window.__votGm.nextId++;"
                + "    window.__votGm.pending[id] = opts;"
                + "    var method = opts.method || 'GET';"
                + "    var headers = opts.headers || {};"
                + "    var data = opts.data || opts.body || '';"
                + "    var headersJson = JSON.stringify(headers);"
                + "    // bridge name is VotBridge (added as JavascriptInterface)\n"
                + "    if (window.VotBridge && window.VotBridge.nativeFetch) {"
                + "      window.VotBridge.nativeFetch(id, opts.url, method, headersJson, data);"
                + "    } else if (window.AndroidInterface && window.AndroidInterface.nativeFetch) {"
                + "      window.AndroidInterface.nativeFetch(id, opts.url, method, headersJson, data);"
                + "    } else { console.warn('VotBridge not found'); if (opts.onerror) opts.onerror({error:'bridge missing'}); }"
                + "    return { abort: function(){ try{ delete window.__votGm.pending[id]; }catch(e){} } };"
                + "  } catch(e){ console.warn('GM_xmlhttpRequest shim error', e); if (opts && opts.onerror) opts.onerror({error: String(e)}); }"
                + "};"
                + "try { globalThis.GM_xmlhttpRequest = window.GM_xmlhttpRequest; } catch(e){}"
                // GM.xmlHttpRequest promise style (GM4)
                + "window.GM = window.GM || {};"
                + "if (!window.GM.xmlHttpRequest) {"
                + "  window.GM.xmlHttpRequest = function(opts){"
                + "    return new Promise(function(resolve, reject){"
                + "      var id = window.__votGm.nextId++;"
                + "      var wrapped = {"
                + "        url: opts.url, method: opts.method || 'GET', headers: opts.headers || {}, data: opts.body || opts.data || '',"
                + "        onload: function(r){ resolve(r); },"
                + "        onerror: function(e){ reject(e); },"
                + "        ontimeout: function(e){ reject(e); }"
                + "      };"
                + "      window.__votGm.pending[id] = wrapped;"
                + "      var headersJson = JSON.stringify(wrapped.headers);"
                + "      if (window.VotBridge && window.VotBridge.nativeFetch) window.VotBridge.nativeFetch(id, wrapped.url, wrapped.method, headersJson, wrapped.data);"
                + "      else if (window.AndroidInterface && window.AndroidInterface.nativeFetch) window.AndroidInterface.nativeFetch(id, wrapped.url, wrapped.method, headersJson, wrapped.data);"
                + "      else reject(new Error('bridge missing'));"
                + "    });"
                + "  };"
                + "}"
                + "if (!window.GM.xmlhttpRequest) window.GM.xmlhttpRequest = window.GM.xmlHttpRequest;"
                + "try { globalThis.GM = window.GM; } catch(e){}"
                // GM storage: sync via VotBridge
                + "window.GM_getValue = window.GM_getValue || function(key, def){"
                + "  try {"
                + "    var bridge = window.VotBridge || window.AndroidInterface;"
                + "    if (!bridge || !bridge.gmGetValue) return def;"
                + "    var raw = bridge.gmGetValue(key, def !== undefined ? JSON.stringify(def) : 'null');"
                + "    if (raw === 'null' || raw === null) return def;"
                + "    try { return JSON.parse(raw); } catch(e){ return raw; }"
                + "  } catch(e){ return def; }"
                + "};"
                + "window.GM_setValue = window.GM_setValue || function(key, value){"
                + "  try {"
                + "    var bridge = window.VotBridge || window.AndroidInterface;"
                + "    if (!bridge || !bridge.gmSetValue) return;"
                + "    var s; try { s = JSON.stringify(value); } catch(e){ s = String(value); }"
                + "    bridge.gmSetValue(key, s);"
                + "  } catch(e){}"
                + "};"
                + "window.GM_deleteValue = window.GM_deleteValue || function(key){"
                + "  try { var b=window.VotBridge||window.AndroidInterface; if(b&&b.gmDeleteValue) b.gmDeleteValue(key); } catch(e){}"
                + "};"
                + "window.GM_listValues = window.GM_listValues || function(){"
                + "  try { var b=window.VotBridge||window.AndroidInterface; if(!b||!b.gmListValues) return []; var raw=b.gmListValues(); var arr=JSON.parse(raw); if(Array.isArray(arr)) return arr; var keys=[]; for(var k in arr) keys.push(k); return keys; } catch(e){ return []; }"
                + "};"
                // GM4 promise storage
                + "if (!window.GM.getValue) window.GM.getValue = function(key, def){ return Promise.resolve(window.GM_getValue(key, def)); };"
                + "if (!window.GM.setValue) window.GM.setValue = function(key, val){ window.GM_setValue(key, val); return Promise.resolve(); };"
                + "if (!window.GM.deleteValue) window.GM.deleteValue = function(key){ window.GM_deleteValue(key); return Promise.resolve(); };"
                + "if (!window.GM.listValues) window.GM.listValues = function(){ return Promise.resolve(window.GM_listValues()); };"
                + "if (!window.GM.getValues) window.GM.getValues = function(obj){"
                + "  try { var res={}; for(var k in obj) res[k]=window.GM_getValue(k, obj[k]); return Promise.resolve(res); } catch(e){ return Promise.resolve({}); }"
                + "};"
                // GM_addValueChangeListener stub (no cross-tab sync in WebView single process, but keep api)
                + "if (typeof GM_addValueChangeListener === 'undefined') window.GM_addValueChangeListener = function(name, cb){ return 0; };"
                + "if (typeof GM_removeValueChangeListener === 'undefined') window.GM_removeValueChangeListener = function(id){};"
                + "if (window.GM && !window.GM.addValueChangeListener) window.GM.addValueChangeListener = function(n,cb){ return window.GM_addValueChangeListener(n,cb); };"
                + "try { globalThis.GM_addValueChangeListener = window.GM_addValueChangeListener; globalThis.GM_removeValueChangeListener = window.GM_removeValueChangeListener; } catch(e){}"
                // ensure globalThis
                + "try { globalThis.GM_getValue = window.GM_getValue; globalThis.GM_setValue = window.GM_setValue; globalThis.GM_deleteValue = window.GM_deleteValue; globalThis.GM_listValues = window.GM_listValues; } catch(e){}"
                ;
    }
}
